### PR TITLE
fix: deprecation warning for contenttypes.generic in Django 1.8

### PR DESCRIPTION
**Pull request by Gagaro**
c.f. https://docs.djangoproject.com/fr/1.8/releases/1.7/#reorganization-of-django-contrib-contenttypes

### CODE REVIEW

**Comment by Gagaro** [comment]
@rbarrois Did you have the time to take a look at this ? Thanks.

**Comment by alexmorozov** [comment]
@rbarrois It would be great to have it merged, as far as Django 1.8 is widely used. Any chances on that?

**Comment by ychab** [comment]
+1

**Comment by marcoimme** [comment]
+1

**Comment by koleror** [comment]
+1

**Comment by koleror** [comment]
I add to fork and apply the patch to make it work on django 1.7.11 so it would be awesome if you could merge this so I could get back to the official repo :)
Thanks

**Comment by rbarrois** [comment]
Thanks for the fix; and sorry for the delay in fixing this :/

**Pull request merged**
